staging-settings:
  user-workflow:
    workflow-name: "token-generation-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../../secrets.yaml"
